module.exports.registerUser = require('./registerUser.service')
module.exports.verifyOtp = require('./verifyOtp.service')
module.exports.login = require('./login.service')
module.exports.logout = require('./logout.service')
module.exports.resendOtp = require('./resendOtp.service')
module.exports.forgetPassword = require('./forgetPassword.service')
module.exports.verifyForgetPasswordOtp = require('./verifyForgetPasswordOTP.service')
module.exports.changePassword = require('./changePassword.service')