module.exports.signup = require('./signup.controller')
module.exports.verifyOtpCode = require('./verifyOtpCode.controller')
module.exports.login = require('./login.controller')
module.exports.logout = require('./logout.controller')
module.exports.resendOtp = require('./resendOtp.controller')
module.exports.forgetPassword = require('./forgetPassword.controller')
module.exports.verifyForgetPasswordOTP = require('./verifyForgetPasswordOTP.controller')
module.exports.changePassword = require('./changePassword.controller')